FROM node:lts-bookworm
ENV DATABASE_URL="mysql://root:p@ssw0rd@swatswap-db:3306/swatswap"
ENV NODE_ENV=production
WORKDIR /usr/src/app
# Leave ports for compose
# EXPOSE 3000
COPY . .
RUN rm -rf node_modules
RUN chown -R node:node /usr/src/app

RUN apt update 2> /dev/null
RUN apt install -y netcat-openbsd 2> /dev/null

USER node
RUN npm install
RUN npx prisma generate
RUN npm run build
