version: "3.4"

# This is the Swatswap production Docker Compose spec
# You MUST have a .env file in this dir with the following vars set:
# MARIADB_ROOT_PASSWORD
# MARIADB_USER
# MARIADB_PASSWORD
# MARIADB_DATABASE
# INTERNAL_PORT

services:
  swatswap:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      # TODO: user perms instead of root
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@swatswap-db:5432/${POSTGRES_DB}"
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - "${INTERNAL_PORT}:3000"
    # Ensure db is migrated to current version, generate bindings, and serve
    command: sh -c "npm start"
  swatswap-db:
    image: postgres:16.1
    volumes:
      - ./db-backup:/backup
      - ./data:/var/lib/mysql
    env_file:
      - .env
