version: "3.4"

services:
  swatswap:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      DOMAIN: http://127.0.0.1:3000/
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
    env_file:
      - .env.local
    command: /bin/sh -c "npm install && timeout 22 sh -c 'until nc -z $0 $1; do sleep 1; done' swatswap-db 5432 && npm run dev"

  swatswap-db:
    image: postgres:16.1
    container_name: swatswap-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: swatswap_db
    volumes:
      - swatswap-db-data:/var/lib/postgresql/data
    env_file:
      - .env.local
    
  swatswap-minio:
    image: minio/minio
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    container_name: swatswap-minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - swatswap-minio-data:/data

volumes:
  swatswap-db-data:
  swatswap-minio-data:
