import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/app/ThemeRegistry";
import SCCSNavBar from "@/components/SCCSNavBar";
import TanstackQueryClientProvider from "@/components/TanstackQueryProvider";
import { NextAuthProvider } from "./NextAuthProvider";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();

  return (
    <NextAuthProvider session={session}>
      <ThemeRegistry options={{ key: "mui" }}>
        <TanstackQueryClientProvider>
          <html lang="en">
            <body className="max-h-full">
              <SCCSNavBar></SCCSNavBar>
              {children}
            </body>
          </html>
        </TanstackQueryClientProvider>
      </ThemeRegistry>
    </NextAuthProvider>
  );
}
